logging:
  level:
    org.springframework: DEBUG

springdoc:
  swagger-ui:
    path: /api/v1/swagger-ui.html
    config-url: /api/v1/v3/api-docs/swagger-config
    disable-swagger-default-url: true
  api-docs:
    path: /api/v1/v3/api-docs