spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.orm.jdbc.bind: INFO

swagger:
  user:
    id: ${SWAGGER_ID}
    password: ${SWAGGER_PASSWORD}

cookie:
  secure: true